/*
 * Copyright (C) 2021 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

plugins {
    id 'com.android.application'
    id 'jacoco'
    id 'aaosApps.buildLogic'
}

android {
    namespace "com.android.car.dialer"

    defaultConfig {
        applicationId 'com.android.car.dialer'
        minSdkVersion 31 // Dialer requires apis that became public in S.
        targetSdkVersion 34
        testInstrumentationRunnerArguments clearPackageData: 'true', coverage: 'true'
    }

    signingConfigs {
        unbundled {
            storeFile file(gradle.ext.unbundledCertPath)
            storePassword 'carapps'
            keyAlias 'carapps'
            keyPassword 'carapps'
        }
    }

    flavorDimensions 'devMode'
    productFlavors {
        fake {
            dimension 'devMode'
            versionNameSuffix '-fake'
            testInstrumentationRunner 'com.android.car.dialer.integration.DialerHiltTestRunner'
            signingConfig signingConfigs.unbundled
        }

        emulator {
            dimension 'devMode'
            versionNameSuffix '-emulator'
            testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
            signingConfig signingConfigs.unbundled
        }

        production {
            dimension 'devMode'
            signingConfig signingConfigs.unbundled
        }
    }

    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            res.srcDirs = ['res']
        }

        production {
            java.srcDirs = ['src']
        }

        emulator {
            java.srcDirs = ['src', 'framework/emulator/src']
            java.excludes = ['com/android/car/dialer/inject/BluetoothSingleHfpModule.java', 'com/android/car/dialer/inject/HfpDataModules.java']
        }

        fake {
            java.srcDirs = ['src']
            java.excludes = ['com/android/car/dialer/inject/BluetoothSingleHfpModule.java']
        }

        androidTestEmulator.setRoot('tests/unittests')
        androidTestEmulator.java.srcDirs = ['tests/unittests/src']
        androidTestFake.setRoot('tests/instrutests')
        androidTestFake.java.srcDirs = ['tests/instrutests/src']
    }

    testOptions {
        animationsDisabled = true
    }

    buildTypes {
        debug {
            testCoverageEnabled = true
            signingConfig android.buildTypes.release.signingConfig
        }
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'),
                    'proguard-rules.pro'
        }
    }

    project.gradle.taskGraph.whenReady {
        connectedEmulatorDebugAndroidTest {
            ignoreFailures = true
        }
        connectedFakeDebugAndroidTest {
            ignoreFailures = true
        }
    }

    // Disable release build for fake and emulator build
    variantFilter { variant ->
        def names = variant.flavors*.name
        if (variant.buildType.name == 'release') {
            if (names.contains('fake') || names.contains('emulator')) {
                setIgnore(true)
            }
        }
    }

    lintOptions {
        // Ignore duplicate resources due to existence of overlayable.xml
        ignore 'DuplicateDefinition'
        // Ignore protected permissions since Dialer is system app
        ignore 'ProtectedPermissions'
        // Ignore ImageView using android:tint
        ignore 'UseAppTint'
        // Ignore quantity errors for translations
        ignore 'MissingQuantity'
        ignore 'ImpliedQuantity'
        // Ignore missing translations
        ignore 'MissingTranslation'

        // Ignore error when a translated string/plural is removed
        ignore 'MissingDefaultResource'

        abortOnError false
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
    implementation files(gradle.ext.lib_car_system_stubs)

    implementation libs.androidx.constraintlayout
    implementation libs.androidx.cardview
    implementation libs.androidx.preference
    implementation libs.androidx.recyclerview
    implementation libs.androidx.lifecycle.common.java8

    implementation libs.hilt.android
    annotationProcessor libs.hilt.android.compiler

    implementation libs.androidx.room.runtime
    annotationProcessor libs.androidx.room.compiler

    implementation libs.androidx.sqlite
    // Implementation of the AndroidX SQLite interfaces via the Android framework APIs.
    implementation libs.androidx.sqlite.framework

    implementation libs.glide
    implementation libs.guava

    api project(':oem-token-lib')
    implementation project(':car-ui-lib')
    implementation project(':car-apps-common')
    implementation project(':car-uxr-client-lib')
    implementation project(':car-assist-lib')
    implementation project(':car-messenger-common')
    implementation project(':car-telephony-common')
    implementation project(':car-dialer-app:framework')

    androidTestImplementation project(':car-ui-lib-testing')
    androidTestImplementation libs.androidx.junit
    androidTestImplementation libs.androidx.test.core
    androidTestImplementation libs.androidx.test.runner
    androidTestImplementation libs.androidx.test.rules
    androidTestImplementation(libs.androidx.espresso.core)
    androidTestImplementation(libs.androidx.espresso.contrib)
    androidTestImplementation(libs.androidx.espresso.intents)
    androidTestImplementation libs.google.truth
    androidTestImplementation libs.dexmaker.mockito.inline

    emulatorImplementation project(':car-dialer-app:testing')
    emulatorImplementation libs.dexmaker.mockito.inline
    androidTestEmulatorImplementation libs.dexmaker.mockito.inline.extended
    androidTestEmulatorImplementation libs.hamcrest

    fakeImplementation project(path: ':car-dialer-app:testing')
    androidTestFakeImplementation libs.hilt.android.testing
    androidTestFakeAnnotationProcessor libs.hilt.android.compiler
    androidTestFakeImplementation libs.androidx.uiautomator
}

android.aaptOptions.additionalParameters "-I", "${projectDir}/../libs/car-ui-lib/oem-tokens/shared-lib/prebuilt/token-shared-lib.apk"
